package bank.management.system;
import javax.swing.*;
import java.awt.*;
import java.util.*;
import com.toedter.calendar.JDateChooser;
public class SignupOne extends JFrame{
    SignupOne(){
        setLayout(null);
        Random ran = new Random();
        long random = Math.abs((ran.nextLong()%9000L)+1000L);
        JLabel formno = new JLabel("Application Form No:  "+ random);
        formno.setFont(new Font("Raleway", Font.BOLD, 38));
        formno.setBounds(140, 20, 600, 40 );
        add(formno);
        JLabel personaldetails = new JLabel("page 1: personal details");
        personaldetails.setFont(new Font("Raleway", Font.BOLD, 22));
        personaldetails.setBounds(290, 80, 400, 30 );
        add(personaldetails);
        JLabel name = new JLabel("Name:");
        name.setFont(new Font("Raleway", Font.BOLD, 20));
        name.setBounds(100, 140, 200, 30 );
        add(name);
        JTextField nameTextField = new JTextField();
        nameTextField.setFont(new Font ("Raleway",Font.BOLD,14));
        nameTextField.setBounds(300, 140,400,30);
        add(nameTextField);
        JLabel FatherName = new JLabel("Father's Name:");
        FatherName.setFont(new Font("Raleway", Font.BOLD, 20));
        FatherName.setBounds(100,190, 200, 30 );
        add(FatherName);
        JTextField FatherNameTextField = new JTextField();
        FatherNameTextField.setFont(new Font("Raleway",Font.BOLD,14));
        FatherNameTextField.setBounds(300,190,400,30);
        add(FatherNameTextField);
        JLabel dob = new JLabel("Date Of Birth:");
        dob.setFont(new Font("Raleway", Font.BOLD, 20));
        dob.setBounds(100, 240, 200, 30 );
        add(dob);
        JDateChooser dateChooser = new JDateChooser();
        dateChooser.setBounds(300,240,400,30);
        dateChooser.setForeground(Color.BLUE);
        add(dateChooser);
        JLabel gender = new JLabel("Gender:");
        gender.setFont(new Font("Raleway", Font.BOLD, 20));
        gender.setBounds(100, 290, 200, 30 );
        add(gender);
        JRadioButton male = new JRadioButton("Male");
        male.setBounds(300, 290, 60, 30);
        male.setBackground(Color.WHITE);
        add(male);
        JRadioButton female = new JRadioButton("Female");
        female.setBounds(450, 290, 120, 30);
        female.setBackground(Color.WHITE);   
        add(female);
        JRadioButton others = new JRadioButton("Others");
        others.setBounds(600, 290, 180, 30);
        others.setBackground(Color.WHITE);
        add(others);
        ButtonGroup gendergroup = new ButtonGroup();
        gendergroup.add(male);
        gendergroup.add(female);
        gendergroup.add(others);
        JLabel Email = new JLabel("Email:");
        Email.setFont(new Font("Raleway", Font.BOLD, 20));
        Email.setBounds(100, 340, 200, 40 );
        add(Email);
        JTextField EmailTextField = new JTextField();
        EmailTextField.setFont(new Font("Raleway",Font.BOLD,14));
        EmailTextField.setBounds(300,340,400 ,30);
        add(EmailTextField);
        JLabel ms = new JLabel("Marital Status:");
        ms.setFont(new Font("Raleway", Font.BOLD, 20));
        ms.setBounds(100,400, 200, 40 );
        add(ms);
        JRadioButton married = new JRadioButton("Married");
        married.setBounds(300, 390, 100, 30);
        married.setBackground(Color.WHITE);
        add(married);
        JRadioButton unmarried = new JRadioButton("Unmarried");
        unmarried.setBounds(450, 390, 100, 30);
        unmarried.setBackground(Color.WHITE);
        add(unmarried);
        JRadioButton other = new JRadioButton("Other");
        other.setBounds(630, 390, 100, 30);
        other.setBackground(Color.WHITE);
        add(other);
        ButtonGroup msgroup = new ButtonGroup();
        gendergroup.add(married);
        gendergroup.add(unmarried);
        gendergroup.add(other);
        JLabel address = new JLabel("Address:");
        address.setFont(new Font("Raleway", Font.BOLD, 20));
       address.setBounds(100,460, 200, 40 );
        add(address);
        JTextField addressTextField = new JTextField();
        addressTextField.setFont(new Font("Raleway", Font.BOLD,14));
        addressTextField.setBounds(300,460,400,30);
        add(addressTextField);
        JLabel City = new JLabel("City");
        City.setFont(new Font("Raleway", Font.BOLD, 20));
        City.setBounds(100,520, 200, 40 );
        add(City);
        JTextField CityTextField = new JTextField();
        CityTextField.setFont(new Font("Raleway", Font.BOLD, 14));
        CityTextField.setBounds(300,520, 400,30);
        add(CityTextField);
        JLabel State = new JLabel("State:");
        State.setFont (new Font("Raleway", Font.BOLD, 20));
        State.setBounds(100, 580, 200,40);
        add(State);
        JTextField StateTextField = new JTextField();
        StateTextField.setFont(new Font("Raleway",Font.BOLD, 14));
        StateTextField.setBounds(300,580,400,30);
        add(StateTextField);
        JLabel Pincode = new JLabel("Pin Code");        
        Pincode.setFont (new Font("Raleway", Font.BOLD, 20));
        Pincode.setBounds(100,640, 400,40 );
        add(Pincode);
        JTextField PincodeTextField = new JTextField();
        PincodeTextField.setFont(new Font("Raleway",Font.BOLD, 14));
        PincodeTextField.setBounds(300,640,400,30);
        add(PincodeTextField);
        JButton next = new JButton("Next");
        next.setBackground(Color.BLUE);
        next.setForeground(Color.WHITE);
        next.setFont(new Font("Raleway",Font.BOLD,14));
        next.setBounds(660,680, 80,30);
        add(next);
        getContentPane().setBackground(Color.WHITE);
        setSize(850, 800);
        setLocation(350, 10);
        setVisible(true);
        
    }
    public static void main(String args[]){
        new SignupOne();
    }
}
